### GET request to example server
POST http://lb-7bcde840.elb.localhost.localstack.cloud:4004/auth/login
content-type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}