### GET request to example server
POST http://localhost:4005/login
content-type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}