### GET request to example server
POST http://lb-fe83e1ce.elb.localhost.localstack.cloud:4003/auth/login
content-type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}