### Create new Patient entity
POST http://localhost:4000/patients
content-type: application/json

{
    "name": "John Doe billing account",
    "email": "john.doe@exampl.com",
    "address": "123 main street",
    "dateOfBirth": "1995-10-12",
    "registeredDate": "2025-11-23"
}
###